/**
 *
 *  Follow.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Follow.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::sqlite3;

const std::string Follow::primaryKeyName = "";
const bool Follow::hasPrimaryKey = false;
const std::string Follow::tableName = "follow";

const std::vector<typename Follow::MetaData> Follow::metaData_={
};
const std::string &Follow::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Follow::Follow(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Follow::Follow(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Follow::Follow(const Json::Value &pJson) noexcept(false)
{
}

void Follow::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}
                                                                    
void Follow::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Follow::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Follow::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Follow::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Follow::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Follow::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Follow::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Follow::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Follow::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Follow::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Follow::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Follow::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Follow::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson, 
                              std::string &err, 
                              bool isForCreation)
{
    switch(index)
    {
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
