/**
 *
 *  Instance.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Instance.h"
#include "Instance.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::sqlite3;

const std::string Instance::primaryKeyName = "";
const bool Instance::hasPrimaryKey = false;
const std::string Instance::tableName = "instance";

const std::vector<typename Instance::MetaData> Instance::metaData_={
};
const std::string &Instance::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Instance::Instance(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Instance::Instance(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Instance::Instance(const Json::Value &pJson) noexcept(false)
{
}

void Instance::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}
                                                                    
void Instance::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Instance::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Instance::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Instance::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Instance::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Instance::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Instance::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Instance::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Instance::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Instance::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Instance::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Instance::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Instance::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson, 
                                std::string &err, 
                                bool isForCreation)
{
    switch(index)
    {
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
void Instance::getInstance(const DbClientPtr &clientPtr, 
                           const std::function<void(std::vector<std::pair<Instance,Instance>>)> &rcb,
                           const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from instance,instance where instance.instance_id = ? and instance.follower_id = instance.id";
    *clientPtr << sql
               << *id_ 
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<Instance,Instance>> ret;
                   ret.reserve(ret.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<Instance,Instance>(
                           Instance(row),Instance(row,Instance::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
